### ISSUE TITLE
 请问一下 把后台用户与前台注册客户混合到 一起可以吗？

### ISSUE THREAD

**Issue by lawtatfaitony** [MEyes/ASP.NET-Identity-User-Management#1]
意思就是前端客户注册的和 员工 都用这个 ASP.NET-Identity-  这个来统一管理。

同时，请问一下 ，注册改为 手机注册 可以 可以吗？ 怎么没看到手机注册的 signin 函数的啊

**Comment by MEyes** [comment]
> 前端客户注册的和 员工 都用这个 ASP.NET-Identity- 这个来统一管理

可以。ASP.NET Identity 用来管理用户，类似于MemberShip，和哪种方式注册没关系。

> 同时，请问一下 ，注册改为 手机注册 可以 可以吗？ 怎么没看到手机注册的 signin 函数的啊

扩展一个手机号码字段作为用户名不就可以了
