### ISSUE TITLE
数据库链接失败。

### ISSUE THREAD

**Issue by aehyok** [MEyes/ASP.NET-Identity-User-Management#2]
数据库链接字符串是没问题的，因为其他项目都是可以的。还望指教一下，试了好几天了，没搞明白，先谢谢大神了。

无法打开登录所请求的数据库 "IdentityDb"。登录失败。
用户 'sa' 登录失败。

说明: 执行当前 Web 请求期间，出现未经处理的异常。请检查堆栈跟踪信息，以了解有关该错误以及代码中导致错误的出处的详细信息。 

异常详细信息: System.Data.SqlClient.SqlException: 无法打开登录所请求的数据库 "IdentityDb"。登录失败。
用户 'sa' 登录失败。

源错误: 

行 35:             if (ModelState.IsValid)
行 36:             {
行 37:                 AppUser user = await UserManager.FindAsync(model.Name, model.Password);
行 38:                 if (user==null)
行 39:                 {

源文件: f:\aehyok\Asp.Net Identity\ASP.NET-Identity-User-Management-master\ASP.NET-Identity-User-Management-master\Users\Controllers\AccountController.cs    行: 37

**Comment by MEyes** [comment]
解决了吗，看异常应该是连接字符串的问题，
1.我看了一下连接字符串，使用了默认的LocalDb， (localdb)\v11.0 这是VS 2013写法。
VS 2015 写法 (Localdb)\MSSqllocaldb。
2.上面没问题的话，那就是Code First 迁移策略的问题，我指定的是NULL 策略，他不会自动产生数据库，因为事先可能存在了。
简单做 把这这句话 注释掉 Database.SetInitializer<AppIdentityDbContext>(new IdentityDbInit());
默认策略是CreateDatabaseIfNotExist，不存在数据库则创建。

**Comment by MEyes** [comment]
我了一下代码，这是最终的代码。应该是之前有数据库了，所以Code First 策略为不自动创建数据库。

你看一下，第一篇文章中是这样写的：
http://www.cnblogs.com/OceanEyes/p/thinking-in-asp-net-mvc-get-started-with-identity.html

```
public class AppIdentityDbContext : IdentityDbContext<AppUser>
   {
       public AppIdentityDbContext() : base("IdentityDb")
       {
       }

       static AppIdentityDbContext()
       {
           Database.SetInitializer<AppIdentityDbContext>(new IdentityDbInit());
       }

       public static AppIdentityDbContext Create()
       {
           return new AppIdentityDbContext();
       }
   }
   public class IdentityDbInit : DropCreateDatabaseIfModelChanges<AppIdentityDbContext>
   {
       protected override void Seed(AppIdentityDbContext context)
       {
           PerformInitialSetup(context);
           base.Seed(context);
       }
       public void PerformInitialSetup(AppIdentityDbContext context)
       {
           //初始化
       }
   }
```

**Comment by aehyok** [comment]
谢谢，已经OK了。
