### ISSUE TITLE
role角色管理页面报错

### ISSUE THREAD

**Issue by BsaGyy** [MEyes/ASP.NET-Identity-User-Management#4]
public ActionResult Index()
        {
            return View(RoleManager.Roles);
        }
view中循环取出user信息时报错，加上tolist后解决，是延迟加载造成的吧

**Comment by MEyes** [comment]
你跟踪下报错信息，Linq 2 Sql 有一些操作不能转换成Sql，ToList()是将数据加载到内存了，然后在对它们进行筛选等。

**Comment by BsaGyy** [comment]
感谢您的回复。
报错语句：@if (role.Users == null || role.Users.Count <= 0)
报错信息：已有打开的与此 Command 相关联的 DataReader，必须首先将它关闭。
跟踪了下view中role是能取到数据，users数据取不到
联想到EF延迟加载，所以才想是不是role数据直接加载了，关联加载的users因为在controller中没有用到所以没加载，在view中使用时报错。

**Comment by MEyes** [comment]
\<add name="IdentityDb" providerName="System.Data.SqlClient" connectionString="Data Source=(localdb)\v11.0;Initial Catalog=IdentityDb;Integrated Security=True;Connect Timeout=15;Encrypt=False;TrustServerCertificate=False; **MultipleActiveResultSets=True"** >

你看一下web.config连接字符串是不是这样写的。

**Comment by MEyes** [comment]
<add name="IdentityDb" providerName="System.Data.SqlClient" connectionString="Data Source=(localdb)\v11.0;Initial Catalog=IdentityDb;Integrated Security=True;Connect Timeout=15;Encrypt=False;TrustServerCertificate=False; MultipleActiveResultSets=True" />

**Comment by BsaGyy** [comment]
哦，我没有用localdb，改成sql server了,
<add name="IdentityDb" connectionString="Server=(local);Database=IdentityDb;uid=sa;pwd=**;" providerName="System.Data.SqlClient" />....

**Comment by MEyes** [comment]
不知道你有没有解决，加这句话了没：MultipleActiveResultSets=True

**Comment by BsaGyy** [comment]
非常感谢，按照您说的加上语句已经解决，非常之感谢！
